
name: 2 TF Plan AWS OIDC-only Native Runner (OIDC Backend)

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        description: Destroy environment?
        required: true
        default: false

  pull_request:
    paths:
    - layers/**

env:
  tf_actions_working_dir: layers/000base

permissions:
  id-token: write
  contents: read
  
jobs:
  plan:
    name: aws cli auth test
    runs-on: ubuntu-latest
    environment: tfplan
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    env:
        NODE_ENV: tfplan
        TF_LOG: "DEBUG"
        BACKEND_BUCKET : ${{ secrets.BACKEND_BUCKET }}
        BACKEND_DYNAMODB_TABLE: ${{ secrets.BACKEND_DYNAMODB_TABLE}}
        BACKEND_KEY: ${{ secrets.BACKEND_KEY}}
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to AWS using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: samplerolesession
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: 'Run aws commands'
      run: |
        aws sts get-caller-identity

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform version
      id: version
      run: terraform --version

    - name: Terraform env
      id: printenv
      run: printenv
    
    - name: Terraform Init OIDC
      id: init-oidc
      run: |
        terraform init \
          -backend-config="bucket=$BACKEND_BUCKET" \
          -backend-config="encrypt=true" \
          -backend-config="region=$AWS_DEFAULT_REGION" \
          -backend-config="key=$BACKEND_KEY" \
          -backend-config="dynamodb_table=$BACKEND_DYNAMODB_TABLE" \
          -reconfigure
      env:
        TF_LOG_PATH: "terraform-oidc.log"  

    - name: Upload the oidc debug log
      uses: actions/upload-artifact@v3
      with:
        name: tf-debug-oidc-log
        path: "${{ env.tf_actions_working_dir }}/terraform-oidc.log"
  
    - name: Calculate destroy arg
      id: destroy_arg
      run: |
        if [ $DESTROY == "true" ]; then
          echo "::set-output name=val::-destroy" 
        else
          echo "::set-output name=val:: "
        fi
      env:
        DESTROY: ${{ github.event.inputs.destroy }}

    - name: Terraform Plan oidc
      id: plan
      run: |
        terraform plan \
          $DESTROY -no-color -out=out.tfplan
      env:
        TF_LOG_PATH: "terraform-plan-oidc.log"

    - name: Upload the plan oidc debug log
      uses: actions/upload-artifact@v3
      with:
        name: tf-debug-plan-oidc-log
        path: "${{ env.tf_actions_working_dir }}/terraform-plan-oidc.log"
    
    - name: Upload the plan
      uses: actions/upload-artifact@v3
      with:
        name: tf-plan-oidc
        path: "${{ env.tf_actions_working_dir }}/out.tfplan"

