
name: 1 Azure CLI Test OIDC

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        description: Destroy environment?
        required: true
        default: false

  pull_request:
    paths:
    - layers/**

env:
  tf_actions_working_dir: layers/000base

permissions:
  id-token: write
  contents: read
  
jobs:
  plan:
    name: az cli auth test
    runs-on: ubuntu-latest
    environment: tfplan
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    env:
        NODE_ENV: tfplan
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run az commands'
      run: |
        az account show
        az group list

   