
name: 3 TF Plan Azure Docker Python

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        description: Destroy environment?
        required: true
        default: false
        
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    environment: tfplan
    continue-on-error: true
    container:
      image: codeinavan/pipeline-toolbox-tf:latest
      env:
        NODE_ENV: tfplan
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        TF_LOG: "DEBUG"
        BACKEND_RG: ${{ secrets.BACKEND_RG}}
        BACKEND_SG: ${{ secrets.BACKEND_SG}}
        BACKEND_CONTAINER: ${{ secrets.BACKEND_CONTAINER}}
        BACKEND_KEY: ${{ secrets.BACKEND_KEY}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Terraform env
      id: printenv
      run: printenv

    - name: Terraform Plan Python with OIDC
      id: plan-oidc
      run: python3 /rackspace/plan-oidc.py
      env:
        ARM_USE_OIDC: true
        TF_LOG_PATH: "/tmp/terraform-oidc.log"

    - name: Upload the oidc debug log
      uses: actions/upload-artifact@v3
      with:
        name: tf-debug-oidc-log
        path: "/tmp/terraform-oidc.log"

    - name: Upload the plan
      uses: actions/upload-artifact@v3
      with:
        name: tf-plan-oidc-result
        path: ${{ github.workspace }}/workspace/**/terraform.*.plan

   