version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.0.0
  terraform: circleci/terraform@3.1.0

jobs:
  verify-install:
    executor: azure-cli/default
    resource_class: small
    parameters:
      client-id: 
        type: env_var_name
        default: AZURE_CLIENT_ID
      tenant-id: 
        type: env_var_name
        default: AZURE_TENANT_ID
      subscription-id:
        type: env_var_name
        default: AZURE_SUBSCRIPTION_ID
      backend-access-key:
        type: env_var_name
        default: BACKEND_ACCESS_KEY
      backend-resource-group-name:
        type: env_var_name
        default: BACKEND_RG
      backend-storage-account-name:
        type: env_var_name
        default: BACKEND_SG      
      backend-container-name:
        type: env_var_name
        default: BACKEND_CONTAINER
      backend-key:
        type: env_var_name
        default: BACKEND_KEY
      oidc_token_file_path: 
        type: string
        default: ./circleci/oidc_token.json
    steps:
      - run:
          name: set env
          command: |
            export ARM_OIDC_TOKEN=$CIRCLE_OIDC_TOKEN
            export ARM_CLIENT_ID="${<< parameters.client-id >>}"
            export ARM_SUBSCRIPTION_ID="${<< parameters.subscription-id >>}"
            export ARM_TENANT_ID="${<< parameters.tenant-id >>}"

      - checkout
      - terraform/install:
          terraform_version: 1.3.1
      
      - run:
          name: Verify Terraform Read of Resource
          command: |
            
            mkdir ./circleci
            echo $CIRCLE_OIDC_TOKEN > << parameters.oidc_token_file_path >>

            export ARM_OIDC_TOKEN=$CIRCLE_OIDC_TOKEN
            export ARM_CLIENT_ID="${<< parameters.client-id >>}"
            export ARM_SUBSCRIPTION_ID="${<< parameters.subscription-id >>}"
            export ARM_TENANT_ID="${<< parameters.tenant-id >>}"
            export ARM_USE_OIDC=true

            cd ./layers/000base

            # OIDC DOESNT WORK ON INIT (YET)
            terraform init \
              -backend-config="resource_group_name=$BACKEND_RG" \
              -backend-config="storage_account_name=$BACKEND_SG" \
              -backend-config="container_name=$BACKEND_CONTAINER" \
              -backend-config="key=$BACKEND_KEY" \
              -backend-config="access_key=$BACKEND_ACCESS_KEY" \
              -reconfigure

            # OIDC WORKS HERE
            terraform plan

            ## terraform apply -auto-approve


workflows:
  example-workflow:
    jobs:
      - verify-install:
          name: verify az and test oidc
          context: 
          - azure-oidc-dev
